version: "3.9"

services:
  fe:
      image: winnerkypt/meetme-frontend-dev:latest
      # build: .
      container_name: react-docker
      networks:  
        - meetme
      environment:
        REACT_APP_BASE_API: ${REACT_APP_BASE_API}
        REACT_APP_BASE_API_SOCKET: ${REACT_APP_BASE_API_SOCKET}
        REACT_APP_BASE_API_PAYMENT: ${REACT_APP_BASE_API_PAYMENT}
networks:
  meetme:  
    external: true